homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url
  # base_url: 192.168.1.141
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.2.0/24

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:

# Manual Devices
mqtt:
  broker: 192.168.1.141
  port: 1883
  protocol: 3.1
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mos_user
  password: !secret mos_pwd
#  broker: !secret cloud_mqtt_server
#  port: !secret cloud_mqtt_port
#  keepalive: 60
#  client_id: home-assitant-1
#  username: !secret cloudmqtt_user
#  password: !secret cloudmqtt_pwd

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/homeassistant/lib/python3.4/site-packages/python_openzwave/ozw_config

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

media_player:
  - platform: plex
  - platform: cast
  - platform: kodi
    name: Front Room Kodi
    host: 192.168.1.148
    username: !secret kodi_user
    password: !secret kodi_pwd

# fly killer
switch:
  - platform: tplink
    host: 192.168.1.168
    name: Fly Killer

# Google Home
emulated_hue:
  host_ip: 192.168.1.141
  listen_port: 80

# nmap tracker
device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.1/24
    home_interval: 10
  - platform: owntracks
    max_gps_accuracy: 200

# Pushbullet
notify:
  - name: Ro
    platform: pushbullet
    api_key: !secret pushbullet_api_key

# Automation rules
automation: !include automation.yaml

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - summary
      - icon
      - nearest_storm_distance
      - temperature
      - pressure
      - humidity
      - wind_speed
  - platform: moon
  - platform: template
    sensors:
      aeotec_multisensor_motion_template:
        value_template: "{%if states.sensor.aeotec_zw100_multisensor_6_burglar_2_10.state == '8' %}motion detected{% elif states.sensor.aeotec_zw100_multisensor_6_burglar_2_10.state == '0' %}standby{% elif states.sensor.aeotec_zw100_multisensor_6_burglar_2_10.state == '3' %}tamper detected{% endif %}"
        friendly_name: "Aeotec PIR"

# Text to speech
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
#    language: de

group: !include groups.yaml
